import os

env = Environment(CXXFLAGS="-std=c++11", CPPPATH=["./include"])
main_src = ["src/main.cpp", "src/eratosthenes.cpp"]
test_src = ["test/test_eratosthenes.cpp", "src/eratosthenes.cpp"]

env.VariantDir(variant_dir="build/eratosthenes/", src_dir="./src", duplicate=0)
env.VariantDir(variant_dir="build/test/", src_dir="./test", duplicate=0)

env.Program(target="build/eratosthenes/eratosthenes", source=main_src)
env.Program(target="build/test/test_eratosthenes", 
                 source=test_src, 
                 LIBPATH=["/usr/local/lib"], 
                 LIBS=["gtest", "pthread"])

env.Alias("test", "build/test/test_eratosthenes")
env.Alias("main", "build/eratosthenes/eratosthenes")

